modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_issue_tracker}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="logo.png"
authors="${mod_author}"
description='''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="${jei_version_range}"
referralUrl="https://github.com/mezz/JustEnoughItems"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="roughlyenoughitems"
type="optional"
versionRange="${rei_version_range}"
referralUrl="https://github.com/shedaniel/RoughlyEnoughItems"
ordering="NONE"
side="BOTH"